---
development:
  cloud_name: <%= ENV["cloud_name"] %>
  api_key: <%= ENV["api_key"] %>
  api_secret: <%= ENV["api_secret"] %>
  enhance_image_tag: <%= ENV["enhance_image_tag"] %>
  static_file_support: <%= ENV["static_file_support"] %>
production:
  cloud_name: <%= ENV["cloud_name"] %>
  api_key: <%= ENV["api_key"] %>
  api_secret: <%= ENV["api_secret"] %>
  enhance_image_tag: <%= ENV["enhance_image_tag"] %>
  static_file_support: <%= ENV["static_file_support"] %>
test:
  cloud_name: <%= ENV["cloud_name"] %>
  api_key: <%= ENV["api_key"] %>
  api_secret: <%= ENV["api_secret"] %>
  enhance_image_tag: <%= ENV["enhance_image_tag"] %>
  static_file_support: <%= ENV["static_file_support"] %>
